### ISSUE TITLE
Feature Request: `watch/inspect` command

### ISSUE THREAD

**Issue by GeRryCh** [plasma-umass/ChatDBG#26]
Would you consider adding a command that inspects the current state of a program at the stopped breakpoint to answer questions such as "Is parameter 'a' equal to parameter 'b'?" This feature would utilize natural language, eliminating the need to declare a local watch with.

**Comment by emeryberger** [comment]
Thanks for the suggestion! If you have a concrete use case where this has come up, we'd be appreciative.

**Comment by GeRryCh** [comment]
Sure! For instance, I'm currently developing an iOS application using the Xcode IDE, which utilizes the lldb debugger. (By the way, the integration of the previously developed `why` functionality worked flawlessly 👏). Now, I'm examining a deeply nested state (e.g., `user.subscription.appStoreSubscription.pastTransaction`, etc). To verify if something is contained there, I either need to unfold the state within the suggested variables for inspection or create a new watch without the assistance of autocomplete (typical Xcode 🤦).

However, providing all the inspectable values of the current application state (offered via the `lldb vo` command, if I'm not mistaken) to GPT makes it much easier to inquire about something like 'do pastTransactions within a user state contain a value?'. Does that make sense?

Thank you.

**Comment by GeRryCh** [comment]
@emeryberger If you believe the feature is worthwhile but it currently seems like an effort, feel free to assign it to me. I'd be happy to at least give it a shot for the `lldb` command.

**Comment by emeryberger** [comment]
Hi @GeRryCh - the latest version of ChatDBG has extensive support for open-ended queries - it now uses the LLM to drive the debugger to find answers to queries. Please take a look - I believe the approach we have implemented is general enough to subsume your use case.

**Comment by GeRryCh** [comment]
Beautiful! Thanks! I'll give it a try.
