### ISSUE TITLE
Feature request: support for Bedrock (via litellm)

### ISSUE THREAD

**Issue by emeryberger** [plasma-umass/ChatDBG#32]
Litellm supports function calls; not sure how well they work but this would enable the use of ChatDBG with other AI providers, notably Amazon AWS Bedrock.

**Comment by ishaan-jaff** [comment]
Thanks for using litellm - do you have any feedback on how we can improve ? 

Regarding function calling here's how to enable it for non openai models https://docs.litellm.ai/docs/completion/function_call#function-calling-for-non-openai-llms

**Comment by ishaan-jaff** [comment]
cc @emeryberger

**Comment by nicovank** [comment]
I actually just added litellm for part of this tool yesterday:

https://github.com/plasma-umass/ChatDBG/blob/c7ea3525d5ded127be64580058a3b16df968c8ca/src/chatdbg/assistant/lite_assistant.py#L103-L112

**Comment by nicovank** [comment]
> How can we improve it?

We already contribute and report issues when we run into them 👍  Thanks!

Pretty sure we only use LiteLLM for ChatDBG API calls at this point so Bedrock, Ollama, etc. should be supported out-of-the-box. @stephenfreund can you confirm and close this?

**Comment by stephenfreund** [comment]
That's right.  Should all work just fine.
