### ISSUE TITLE
CDS Data

### ISSUE THREAD

**Issue by Alhbadmus** [plasma-umass/ChatDBG#52]
GenerateRandomResponses()
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets("Responses") ' Change to your sheet name
    Dim i SubAs Long
    Dim lastRow As Long
    Dim age As Integer
    Dim gender As String
    Dim education As String
    Dim occupation As String
    Dim residenceLength As String
    Dim impactRating As String
    Dim needsAddressed As String
    Dim infrastructureImprovements As String
    Dim satisfactionQuality As String
    Dim communitySatisfaction As String
    Dim areasForImprovement As String
    Dim capacityInfluence As String
    
    ' Clear previous responses
    ws.Cells.ClearContents
    
    ' Set headers for the response columns
    ws.Range("A1").Value = "Respondent ID"
    ws.Range("B1").Value = "Age"
    ws.Range("C1").Value = "Gender"
    ws.Range("D1").Value = "Educational Level"
    ws.Range("E1").Value = "Occupation"
    ws.Range("F1").Value = "Length of Residence"
    ws.Range("G1").Value = "Impact Rating"
    ws.Range("H1").Value = "Needs Addressed"
    ws.Range("I1").Value = "Infrastructure Improvements"
    ws.Range("J1").Value = "Satisfaction Quality"
    ws.Range("K1").Value = "Community Satisfaction"
    ws.Range("L1").Value = "Areas for Improvement"
    ws.Range("M1").Value = "Capacity Influence"

    ' Define possible responses for each question
    Dim genders As Variant
    genders = Array("Male", "Female", "Other")
    
    Dim educationLevels As Variant
    educationLevels = Array("Primary", "Secondary", "Tertiary", "Other")
    
    Dim residenceLengths As Variant
    residenceLengths = Array("Less than 1 year", "1-5 years", "More than 5 years")
    
    Dim impactRatings As Variant
    impactRatings = Array("Very High Impact", "High Impact", "Moderate Impact", "Low Impact", "No Impact")
    
    Dim needsAddressedOptions As Variant
    needsAddressedOptions = Array("Employment opportunities", "Health services", _
                                   "Education and literacy programs", "Community engagement and empowerment")
    
    Dim infrastructureImprovementsOptions As Variant
    infrastructureImprovementsOptions = Array("Roads and transportation facilities", _
                                               "Water supply and sanitation services", _
                                               "Community centres or recreational facilities", "Other")
    
    Dim satisfactionQualityOptions As Variant
    satisfactionQualityOptions = Array("Very Satisfied", "Satisfied", "Neutral", _
                                        "Dissatisfied", "Very Dissatisfied")
    
    Dim areasForImprovementOptions As Variant
    areasForImprovementOptions = Array("Communication with the community", _
                                        "Quality of services provided", _
                                        "Frequency of community engagement activities", "Other")

    Dim capacityInfluenceOptions As Variant
    capacityInfluenceOptions = Array("Very Positively", "Positively", _
                                      "Neutral", "Negatively", "Very Negatively")

    
    ' Generate random responses for 200 respondents
    For i = 2 To 201 ' Start from row 2 to row 201 for 200 respondents
        
        ' Generate random demographic data
        age = Int((70 * Rnd) + 18) ' Random age between 18 and 87
        
        gender = genders(Int(Rnd * UBound(genders) + 1))
        education = educationLevels(Int(Rnd * UBound(educationLevels) + 1))
        occupation = "Occupation" & (Int((50 * Rnd) + 1)) ' Placeholder for occupation
        
        residenceLength = residenceLengths(Int(Rnd * UBound(residenceLengths) + 1))
        
        ' Generate random evaluation responses
        impactRating = impactRatings(Int(Rnd * UBound(impactRatings) + 1))
        
        ' Select random needs addressed (up to 2)
        needsAddressed = ""
        For j = 0 To Int(Rnd * (UBound(needsAddressedOptions) + 1))
            If j > 0 Then needsAddressed = needsAddressed & ", "
            needsAddressed = needsAddressed & needsAddressedOptions(Int(Rnd * UBound(needsAddressedOptions)))
        Next j
        
        ' Select random infrastructure improvements (up to 2)
        infrastructureImprovements = ""
        For j = 0 To Int(Rnd * (UBound(infrastructureImprovementsOptions) + 1))
            If j > 0 Then infrastructureImprovements = infrastructureImprovements & ", "
            infrastructureImprovements = infrastructureImprovements & infrastructureImprovementsOptions(Int(Rnd * UBound(infrastructureImprovementsOptions)))
        Next j
        
        satisfactionQuality = satisfactionQualityOptions(Int(Rnd * UBound(satisfactionQualityOptions) + 1))
        
        communitySatisfaction = satisfactionQualityOptions(Int(Rnd * UBound(satisfactionQualityOptions) + 1))
        
        areasForImprovement = ""
        For j = 0 To Int(Rnd * (UBound(areasForImprovementOptions) + 1))
            If j > 0 Then areasForImprovement = areasForImprovement & ", "
            areasForImprovement = areasForImprovement & areasForImprovementOptions(Int(Rnd * UBound(areasForImprovementOptions)))
        Next j
        
        capacityInfluence = capacityInfluenceOptions(Int(Rnd * UBound(capacityInfluenceOptions) + 1))
        
        ' Fill in the worksheet with generated data
        With ws.Rows(i)
            .Cells(1, 1).Value = i - 1 ' Respondent ID
            .Cells(1, 2).Value = age ' Age
            .Cells(1, 3).Value = gender ' Gender
            .Cells(1, 4).Value = education ' Educational Level
            .Cells(1, 5).Value = occupation ' Occupation
            .Cells(1, 6).Value = residenceLength ' Length of Residence in Agbara LCDA
            .Cells(1, 7).Value = impactRating ' Impact Rating
            .Cells(1, 8).Value = needsAddressed ' Needs Addressed
            .Cells(1, 9).Value = infrastructureImprovements ' Infrastructure Improvements
            .Cells(1, 10).Value = satisfactionQuality ' Satisfaction Quality
            .Cells(1, 11).Value = communitySatisfaction ' Community Satisfaction
            .Cells(1, 12).Value = areasForImprovement ' Areas for Improvement
            .Cells(1, 13).Value = capacityInfluence ' Capacity Influence
        End With

    Next i
    
End Sub

**Comment by nicovank** [comment]
Assuming spam.
