### ISSUE TITLE
Is it not available to analyse the core dump file??

### ISSUE THREAD

**Issue by swapniil** [plasma-umass/ChatDBG#8]
I'm trying to load a core and its binary.
While trying with the `why` I'm getting

```
(gdb-ChatDBG) why
Execution stopped at a breakpoint, not an error.
(gdb-ChatDBG) 
```

Is it not supported yet?

**Comment by emeryberger** [comment]
Thanks for the report! This is now fixed as of version 0.0.13 (fix here: https://github.com/plasma-umass/ChatDBG/commit/ef89ded672ccaea80b69cb7021b76566d9bc0d90).

Note for future reference: [here's how to find core files in Ubuntu](https://askubuntu.com/a/1349048/456766).
